
workflows:
  android-release:
    name: Android Release (in-repo keystore)
    environment:
      flutter: stable
    scripts:
      - name: Prepare
        script: |
          echo "Preparing build..."
          if [ -f android/app/keystore/my-release-key.jks ]; then
            export KEYSTORE_FILE=android/app/keystore/my-release-key.jks
            echo "Using in-repo keystore"
          fi
          if [ -n "${ANDROID_FIREBASE_SECRET:-}" ]; then
            mkdir -p android/app
            echo "$ANDROID_FIREBASE_SECRET" | base64 --decode > android/app/google-services.json
            echo "Decoded google-services.json"
          fi
      - name: Get packages
        script: flutter pub get
      - name: Build release
        script: |
          if [ -f "$KEYSTORE_FILE" ]; then
            echo "Building release APK and AAB"
            flutter build apk --release -t lib/main.dart
            flutter build appbundle --release -t lib/main.dart
          else
            echo "No keystore, building debug APK"
            flutter build apk --debug -t lib/main.dart
          fi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
